### ISSUE TITLE
Switch digital ocean account (because we run out of money)

### ISSUE THREAD

**Issue by Myssenberg** [devops2024-group-e/itu-minitwit#141]
Right now we are running on @Myssenberg Digital Ocean account and credit, which will run out on the 16th of April 2024. Therefore we have to move our VM's to another person's account before that date.
- [x] Figure out if we can setup a new account with money
- [x] Create configuration management service
   - [x] Enable the ansible github workflow
- [x] Prepare lift and shift solution for the database
   - [x] #157  
- [x] #215 
- [x] Extract Dashboards and connection configurations for Grafana and Prometheus
- [x] Setup Infrastructure at the new account
   - [x] Run Pulumi workflow
   - [x] Change connection string to the new database
       - [x] Make test call to get latest
       - [x] Make test in UI
       - [ ] Increase droplet limit (On going)
- [x] Prepare endpoint change in `devops-repo`
- [x] Perform db migration with `pg-migrate.sh`

Digital Ocean claims that we can get the full year of credits from Github Educational Pack via this link: https://cloud.digitalocean.com/github-student-pack?onboarding_origin=github-student-pack&activation_redirect=%2Fgithub-student-pack&i=70ba77

**Comment by arnenator** [comment]
@amalieboegild could create an account with the credits. She has invited us to her team now

**Comment by arnenator** [comment]
This is done. We are now using the new digitalocean account. However, we still haven't heard anything from digitalocean regarding increasing the droplet limit, which would be nice to actually have 😫
