### ISSUE TITLE
Research product alternatives to Vagrant

### ISSUE THREAD

**Issue by Pinkvinus** [devops2024-group-e/itu-minitwit#198]
We have had a lot of problems regarding vagrant like:

- Other devs need their pub key to be added manually to the server
- CI/CD doesn't work with vagrant

Research and reason why we should make this change in notion

**Comment by arnenator** [comment]
I have added some research comments in the decision log. The reason why I have added this to review is because @devops2024-group-e/dev-team has to take a decision about which tool to use.
