### ISSUE TITLE
Add a docker file that can run the minitwit program🐳

### ISSUE THREAD

**Issue by Arneproductions** [devops2024-group-e/itu-minitwit#41]
Create dockerfiles for the following applications:
- [x] Minitwit UI
- [x] Minitwit API
- [x] (Database)

**Comment by Arneproductions** [comment]
We have created a working dockerfile for the minitwit UI app. However, we still need to create one where both the api and ui app connects to an external database.

**Comment by Pinkvinus** [comment]
We have created docker hub repositories for the corresponding docker images. The first of which can run on the VM
