### ISSUE TITLE
Clean the minitwit repository 🧽

### ISSUE THREAD

**Issue by arnenator** [devops2024-group-e/itu-minitwit#42]
Since we are going to take ownership of the application, then we need to clean up the application directory so that it is easier to work with.
### Task list
- [x] #58
- [x] #59
- [x] #60
- [x] #57
- [x] #83
- [x] #91

**Comment by Arneproductions** [comment]
@Pinkvinus why did you move it to blocked?

**Comment by Pinkvinus** [comment]
@Arneproductions It was because, in order to move this work item to done, the subitems need to be done first, thereby making it blocked, but i see why it could also go in "in progress"
