### ISSUE TITLE
Setting up VMs in Digital Ocean with vagrant file 🌊

### ISSUE THREAD

**Issue by sarahcecilie** [devops2024-group-e/itu-minitwit#56]

**Comment by Pinkvinus** [comment]
- [ ] Change vagrant file in the root of the repository
- [ ] Pull down the docker images to the VM
- [ ] Make a guide s.t. everyone can access the VMs using vagrant.

**Comment by Arneproductions** [comment]
@Pinkvinus I think that i have figured out what to do now. At least i have an idea of how we setup our stuff more securely than we do now. I was looking into how to use our github container registry as a way to get our images from. And I think that i have found a way by using a token with limited permission that we can create. So we are going to change our container registry today! 

As a reference i found this guy who has the same idea as me: https://www.youtube.com/watch?v=f5AlQE0i5m0
