### ISSUE TITLE
Add testing to our GitHub workflow

### ISSUE THREAD

**Issue by amalieboegild** [devops2024-group-e/itu-minitwit#74]
As of now, our workflow only includes building and deploying. We need to include some testing in the workflow, such that the code only gets deployed if all testing succeeds. The hard part about this is that Helge uses docker compose to achieve this, and since we don't use docker compose we need to figure out how to do ourselves.

**Comment by Pinkvinus** [comment]
In order to test the workflow you can use the following command:

`git commit --allow-empty -m "Empty-Commit"`

Which allows you to make empty git commits

**Comment by Arneproductions** [comment]
> In order to test the workflow you can use the following command:
> 
> `git commit --allow-empty -m "Empty-Commit"`
> 
> Which allows you to make empty git commits

I would instead recommend branch out and use the "Run workflow" feature in the Github Actions view. Here you can specify which branch you want to run your workflow on. BUT be careful. Running the current workflow will push changes to production (i.e. ContinousDeployment). We do not want that. So when testing the workflow please make sure that you comment out the part where the workflow deploys the changes to production.
