### ISSUE TITLE
Introduce database abstraction layer

### ISSUE THREAD

**Issue by amalieboegild** [devops2024-group-e/itu-minitwit#80]
- [x] Make user repository (Amalie)
- [x] Make test for user repository
- [x] Make messages repository (Amalie)
- [x] Make test for messages repository (Amalie)
- [x] Make latest repository (My)
- [x] Make tests for latest repository (My)
- [x] Make followers repository (My)
- [x] Make tests for followers repository (My)
- [x] Implement repositories in Simulator as well (Amalie)
- [ ] Fix integration tests that fail (My)

**Comment by Pinkvinus** [comment]
Instead of executing SQL code on the database in every single method, you can make a database abstraction layer (see [BDSA content](https://github.com/BDSA-2021/BDSA21-Say-AAAAAA/blob/master/SELearning.Infrastructure/Content/ContentRepository.cs))

**Comment by Arneproductions** [comment]
You need to fix your code such that it passes the integration tests as well
