### ISSUE TITLE
Add workflow that only tests when a PR is created 🙅‍♂️ 🙅‍♀️ 

### ISSUE THREAD

**Issue by Arneproductions** [devops2024-group-e/itu-minitwit#90]
# What is it that we want?
At the moment we do not have any validation that our code works as intended when a PR is submitted. What we want to have is a check that is being run every time new code is pushed to a branch where a PR has been created. 

## What should happen when the workflow is done with testing changes?
So we want to deny the ability to merge a PR if the tests reports a failure and we want to allow the ability to merge if tests are green and the PR has been approved

**Comment by Pinkvinus** [comment]
This issue was resolved in #112 , and will be considered closed
